[project]
name = "pipeline_simple"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "dagster>=1.10",
    "dagster-webserver>=1.10",
    "dagster-postgres>=0.26",
    "dagster-dbt>=0.26",
    "dbt-snowflake>=1.9",
    "pandas>=2.0",
    "pyarrow>=15.0",
    "snowflake-connector-python>=3.7",
    "tabulate>=0.9",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["pipeline_simple*"]

[tool.dagster]
module_name = "pipeline_simple"
code_location_name = "pipeline_simple"
